# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- main

variables:
  # Agent VM info
  vmImageName: 'ubuntu-latest'
  currentDate: $[ format('{0:yyyy}.{0:MM}.{0:dd}', pipeline.startTime) ]

  # Container registry service connection established during pipeline creation
  dockerRegistryServiceConnection: 'ttranPipeline-sc'
  imageRegistry: 'ttran-a9bufhazdagrd7hy.azurecr.io'
  imageRepository: 'springboot-jpa-many-to-many'
  dockerfilePath: '$(Build.SourcesDirectory)/Dockerfile'
  imageTag: '$(currentDate)-$(Build.SourceBranchName)-$(Build.SourceVersion)'

stages:
  - stage: Build
    displayName: Build and push image
    jobs:
      - job: Build
        displayName: Build
        pool:
          vmImage: $(vmImageName)
        steps:
          - task: Maven@3
            inputs:
              mavenPomFile: 'pom.xml'
              mavenOptions: '-Xmx3072m'
              javaHomeOption: 'JDKVersion'
              jdkVersionOption: '1.21'
              jdkArchitectureOption: 'x64'
              publishJUnitResults: true
              testResultsFiles: '**/surefire-reports/TEST-*.xml'
              goals: 'package'

          - task: Docker@2
            displayName: Build and push an image to container registry
            inputs:
              command: 'buildAndPush' # 'buildAndPush' | 'build' | 'push' | 'login' | 'logout' | 'start' | 'stop'. Required. Command. Default: buildAndPush.
              containerRegistry: $(dockerRegistryServiceConnection)
              repository: $(imageRepository)
              Dockerfile: $(dockerfilePath) # string. Required when command = build || command = buildAndPush. Dockerfile. Default: **/Dockerfile.
              tags: |
                $(imageTag)

          - bash: |
              docker images
              docker save -o target/image.tar $(imageRegistry)/$(imageRepository):$(imageTag)
              ls -ltr
              ls -ltr target/
            displayName: Prepare image artifact

          - task: PublishBuildArtifacts@1
            displayName: 'Publish Image Artifact'
            condition: succeeded() # The condition argument specifies to run the task only when the previous task succeeds.
            inputs:
              pathToPublish: '$(System.DefaultWorkingDirectory)/target/image.tar' # wildcard are not supported
#              artifactName: 'ttranapp' # default artifact name is 'drop'

  - stage: Deploy
    displayName: Deploy to environment
    dependsOn: Build
    jobs:
      - deployment: Deploy
        pool:
          vmImage: $(vmImageName)
        environment:
          name: dev
          resourceType: VirtualMachine
          tags: web1
        variables:
          - group: ttran-release
        strategy:
          runOnce:
            deploy:
              steps:
#                - download: current
#                  artifact: drop
                - script: |
                    hostname
                    image_name="$(imageRepository):$(imageTag)"
                    container_name="app"
  
                    # Login to Azure Container Registry (if not already logged in)
                    # az acr login --name $(imageRegistry)
  
                    # Stop and remove the existing container (if it exists)
                    docker stop $container_name || true
                    docker rm $container_name || true
  
                    # Pull the latest image from ACR
                    docker pull $image_name
  
                    # Run the new container
                    docker run --name $container_name -d -p 8080:8080 $(imageRepository):$(imageTag)